### ISSUE TITLE
German watchface toggles between `Viertel` and `fünfzehn`

### ISSUE THREAD

**Issue by Steinblock** [samuelmr/garmin-abouttime#1]
If the time is about quarter to or quarter past full hour the clock sometimes displays `Viertel vor fünf` and sometimes `fünfzehn vor fünf`.

The text seems to change every few seconds which is anoying.

I assume changing the line 

```
  <string id="quarter">Viertel|fünfzehn</string>
```

in https://github.com/samuelmr/garmin-abouttime/blob/master/resources-deu/strings.xml

to 

```
  <string id="quarter">viertel</string>
```

could solve this. Also `viertel` should be lowercase to make it consistent.

**Comment by samuelmr** [comment]
Thanks for raising the issue!

The text is intended to be variable. It should only change once a minute. The reason for rapid changes is [a bug in Garmin's ConnectIQ SDK](https://forums.garmin.com/forum/developers/connect-iq/1437584-bug-in-connect-iq-3-0-6-sdk-but-same-in-3-07).

I agree it's annoying. I'll apply the fix you suggested and publish a new version.
