### ISSUE TITLE
Venu issue. 

### ISSUE THREAD

**Issue by Switnl** [samuelmr/garmin-abouttime#13]
Installed the Dutch version on my Venu. It only shows watchface for <0.5sec then goes black. Only way to view again is swipe up/down and back to watchface.
I really like the design /idea!

**Comment by samuelmr** [comment]
Thanks for the report!

I have received reports from others as well (Fenix 5 and Vivoactive4).

Probably related to 9ddeba3d9e36a04a135760c03b931ff7e0f08a38 or 685e98499f898b99b2478803a88c47dcac83ade5

I'll investigate.

**Comment by samuelmr** [comment]
I published a new Dutch version 5.4.7 to the store.

Can you upgrade and comment on whether the issue still persists?

**Comment by Switnl** [comment]
It works! Thanks. 5stars for you!

Op vr 22 mei 2020 07:56 schreef Samuel Rinnetmäki <notifications@github.com
