### ISSUE TITLE
Update on Garmin Store

### ISSUE THREAD

**Issue by valipod** [samuelmr/garmin-abouttime#19]
I have seen that the code has been updated for a while now, but in the Garmin Store only a handful of the faces appear updated on June 15th (ex. the one in Czech language), while most of them are with the version from March 30th (including the main English version). Is the push to the store an automated procedure for all language versions?

**Comment by samuelmr** [comment]
HI!

Thanks for reaching out.

Unfortunately, I haven't found a way to push the updates to the store automatically. So it's manual work, requiring 1 to 2 minutes per version.

After significant changes, I usually update first only a couple of translations. If there is no feedback, I assume everything works and continue updating other versions. This time, at least one Venu user sent a complaint regarding the font in Venu. I've been abroad, away from the keyboard, and haven't yet decided what to do about that issue.

Is there a specific language version you're waiting for?

**Comment by samuelmr** [comment]
I uploaded a new Romanian version on July 13th. Today I pushed yet another version, using Noto Sans as the font.

**Comment by valipod** [comment]
Thank you!
