### ISSUE TITLE
Text lines overlaps (polish version)

### ISSUE THREAD

**Issue by 6e2f61** [samuelmr/garmin-abouttime#22]
Hi,

on Fenix 6s in both polish versions (everyday and alternative) text between rows overlaps. Before last update (alternative version) everything was fine. There were some space between horizontal text lines. Now they overlaps each other. Can space between horizontal text lines be increased a bit?

I tried to flip `smaller font` option, but this does not change anything.

Example how it looks like now with `small fonts` option on. Especially in second line letter `p` overlaps letter `ó` in 3rd row. There are much more examples when letters like `ą, ę, g, j, p, y, b, ć, d, f, h, i, k, l, ł, ó, ś, t, ź, ż` touches edge of other letter ;)

![image](https://user-images.githubusercontent.com/59164897/206861031-3fe47bcb-8513-4b05-a49d-354a8006617b.png)

**Comment by samuelmr** [comment]
Fixed in 59349fc66a82ec0e2bda79add354274bb1a123bd (version 7.2.6)
