### ISSUE TITLE
Watch face not working on Forerunner 645 Music

### ISSUE THREAD

**Issue by vigliensoni** [samuelmr/garmin-abouttime#23]
The awesome About Time watch face stopped working on my Garmin 645 Music watch.

It is installed in the watch (I can see it and change its configuration in Garmin Connect), but it doesn't appear as one of the available watch faces.

Any clues?

Thank you!

**Comment by samuelmr** [comment]
Sorry for the delay. This issue had fallen through the cracks.

I don't have a clue about what would prevent the watch face from being displayed in the list of available watch faces in the watch.

Which translation are you using?

Can you try uninstalling and re-installing the watch face?

**Comment by vigliensoni** [comment]
Thanks for replying.

I'm using the English one and have tried uninstalling and installing. Still, the same issue.

**Comment by samuelmr** [comment]
I can confirm that the watch face doesn't work in FR 645 M. It does work in the simulator, though.

I was able to get my hands on an actual FR645M device and start investigating.

**Comment by samuelmr** [comment]
Seems to be linked to this: https://forums.garmin.com/developer/connect-iq/f/discussion/324531/major-issues-with-custom-fonts-after-latest-device-fw-updates/1577003#1577003
