### ISSUE TITLE
No "do not disburb icon"

### ISSUE THREAD

**Issue by claudiosala80** [samuelmr/garmin-abouttime#24]
Hello.

Probably this is not the right way, but I found a fix for the "not disturb" icon that doesn't appear for some devices (we spoke about it time ago).

At line 247 if you replace the AND with an OR it seems working (for the simulation I did, for Swim 2)
    var isSleepTime = now.greaterThan(today.add(profile.sleepTime)) ||
                      now.lessThan(today.add(profile.wakeTime));

Let me know and apologize me if I used this channel.

Regards
Claudio

**Comment by samuelmr** [comment]
This is fixed already in version 7.13.0 (on Sep 25th). Forgot to close the issue.
